### ISSUE TITLE
다른 애드온과의 호환성 문의

### ISSUE THREAD

**Issue by socialskyo** [cydemo/rx-addon-ap_pager#1]
안녕하세요. 윤삼님

// JS 스크립트 로드
Context::loadFile(array(__DIR__ . '/script.js', 'body', '', null), true);

이런 식으로 스크립트가 로드 되는 애드온을 사용 하고 있습니다. (유료라서 여기에 공개 하지 못하는 점 죄송합니다.)

ajax 모드일때 페이지를 넘기면 해당 애드온의 스크립트가 페이징을 누르는 만큼 계속 로드가 되어 추가 적용이 되는 현상이 있습니다. 
혹시 이런 경우 스크립트가 글 읽기시 최초 한번만 실행 되거나 ajax 버튼에 반응 하지 않기 위한 조언 해주실 만한 아이디어가 있으실까요?

**Comment by cydemo** [comment]
https://github.com/cydemo/rx-addon-ap_pager/blob/c80478ab8787c0004d07bc93c2bbdcae1967f8b9/skins/default/js/default.js#L103-L115
여기서 다른 애드온의 js를 재실행하게 되는데요.
애드온 js 목록 생성할 때 말씀하신 애드온을 예외 처리하면 될 것 같아요.

**Comment by socialskyo** [comment]
@cydemo 감사합니다. 그런데 제가 코드에 ㅋ 도 모르는 사람인지라 저기서 애드온 예외 처리를 어떻게 해야 하는지 잘 모르겠습니다.

**Comment by cydemo** [comment]
저도 잘은 모르는데...ㅜ
해당 애드온의 폴더 이름이 어떻게 되나요?

**Comment by socialskyo** [comment]
wst_unlink_document 입니다. T.T

**Comment by cydemo** [comment]
요것도 주말 중에 코드를 좀 짜보겠습니다!!

**Comment by socialskyo** [comment]
@cydemo 감사합니다!!

**Comment by cydemo** [comment]
@socialskyo 위에 언급했던 구문을 아래처럼 바꿔서 테스트해주실 수 있을까요?

```
var addons_scripts = []; 
if ( pager_minify_scripts ) 
{ 
	$('body script[src^="/files/cache/assets/minified/"]').each(function(i, v) { 
		if ( v.attr('src').indexOf('wst_unlink_document') === -1 ) {
			addons_scripts[i] = $(this).attr('src'); 
	 	}
	}); 
} 
else 
{ 
	$('body script[src^="/addons/"]').each(function(i, v) {
		if ( v.attr('src').indexOf('wst_unlink_document') === -1 ) {
			addons_scripts[i] = $(this).attr('src'); 
	 	}
	}); 
}
```

**Comment by socialskyo** [comment]
@cydemo 일이 있어 테스트가 늦었습니다. 잘되는 것 같습니다. ^^

추신 >> 이 패치 적용후 가끔씩 본문 길이가 1페이지 문장 길이 기준으로 고정 되는 경우가 있긴 한데 그건 그 나름 대로 좋은 것 같기도 해서 버그라고 생각 되지 않습니다.

**Comment by socialskyo** [comment]
@cydemo 아..반대로 페이지 길이가 1페이지 기준으로 고정이 되니 다음 페이지의 내용이 1페이지 보다 길면 본문이 틀어지는 문제가 있네요. 링크는 쪽지로 보내드려봤습니다.

**Comment by socialskyo** [comment]
@cydemo 참고로 ajax 모드에서만 그렇습니다.

**Comment by cydemo** [comment]
@socialskyo 보내주신 링크는 ajax 모드가 해제된 건가요?
본문 길이 문제 없이 잘 나오는 것 같아서요.

**Comment by socialskyo** [comment]
@cydemo 네.길이 문제 때문에 해제 해두었습니다.

**Comment by cydemo** [comment]
@socialskyo 
https://github.com/cydemo/rx-addon-ap_pager/blob/c80478ab8787c0004d07bc93c2bbdcae1967f8b9/skins/default/js/default.js#L120-L124

여기에 보면 setTimeout의 딜레이 시간이 100으로 걸려 있는데요.
왠지 이 숫자를 늘려서 높이를 맞출 수 있겠다는 예감이 듭니다ㅎ

테스트 부탁드려요~~ 적어도 200에서 넉넉히 400 정도요...?

**Comment by socialskyo** [comment]
@cydemo 800까지 하나씩 해봤는데..다른 변화는 없었습니다.

1. 그리고 보니까 길이가 긴 이미지인경우 인식을 못하는 문제가 있는 것 같습니다. 혹시 몰라 직접 보시라고 ajax 로 다시 돌려 두었습니다.

2. 추가로 이번 또 알게 되었는데 ajax + 2페이지에 유튜브 파싱의 경우 2페이지의 유튜브는 나오질 않는 것 같습니다.
해당 이슈의 url은 쪽지로 보내놓겠습니다.

추신 : 최초 오픈한 주제와 내용이 좀 멀어지는데 원하시면 개별 주제로 다시 등록 하겠습니다

**Comment by cydemo** [comment]
@socialskyo 제 예감이 틀렸나봅니다ㅠㅠ 어차피 연관되는 문제니 여기 이슈에서 계속 이야기해주시면 될 것 같아요;;;

1. 길이 문제는 좀 시간을 두고 고민을 해봐야 할 것 같습니다. 정 안되면 ajax 기능을 포기해야 할지도 모르겠어요ㅜ
2. ajax를 실행할 때마다 페이지에 로딩된 js를 재실행하도록 했었습니다. 주로 다른 애드온의 js를 재실행하는 것만으로도 문제가 없었죠. 근데 애드온 개발 당시만 해도 파서링크 모듈이 등장하기 전이었나 그랬을 거예요. 그래서 modules를 경로로 가진 js 재실행은 안 되는 거죠.

**Comment by cydemo** [comment]
그냥 이렇게 가는 게 어떨까 합니다.
(제가 이 상황을 테스트하기가 어렵다보니 귀찮게만 해드리네요ㅜㅜ)
https://github.com/cydemo/rx-addon-ap_pager/blob/c80478ab8787c0004d07bc93c2bbdcae1967f8b9/skins/default/js/default.js#L103-L124
대신에 이렇게요.

```
				var addons_scripts = [];
				if ( pager_minify_scripts )
				{
					$('body script[src^="/files/cache/assets/minified/"]').each(function(i) {
						if ( v.attr('src').indexOf('wst_unlink_document') === -1 ) {
							addons_scripts[i] = $(this).attr('src');
						}
					});
					addons_scripts.push('/files/cache/assets/minified/modules.parserlink.tpl.js.ap_parser.min.js');
				}
				else
				{
					$('body script[src^="/addons/"]').each(function(i) {
						if ( v.attr('src').indexOf('wst_unlink_document') === -1 ) {
							addons_scripts[i] = $(this).attr('src'); 
					 	}
					});
					addons_scripts.push('/modules/parserlink/tpl/js/ap_parser.js');
				}
				
				$.each(addons_scripts, function(index, value) {
					$.getScript(value);
					if ( index === addons_scripts.length - 1 )
					{
						setTimeout(function() {
							$(c).css({
								height : 'auto'
							});
						}, 100);
					}
				});
```

**Comment by socialskyo** [comment]
@cydemo 뭔가 잘 모르겠지만 위 내용을 적용하니 문제가 해결 되었지만 ajax 가 실행 안되는 것과 동일한것 같습니다. ajax 사용 안함과 어떤 차이가 있는 건지요? 

추신 제가 오히려 죄송합니다. 피드백을 드려서 괜히 힘들게 T.T

**Comment by cydemo** [comment]
ajax 실행 안 할 때처럼 주소창에 upage 파라미터가 붙는다구요?
그러면 안되는데요ㅜㅜㅜㅜ

**Comment by socialskyo** [comment]
@cydemo 네. 붙더라고요.
'jQuery(function($) {

	var c = '.ap_pager_content',
		b = '.ap_navi_button',
		n = '.ap_page_navigation',
		l = '.ap_pager_loading';

	if ( pager_swipe )
	{
		var upage = 1;
		if ( current_url.getQuery('upage') )
		{
			upage = Number(current_url.getQuery('upage'));
		}
		var total_page = Number($(n).find('li:last').text());
		var href = '';

		$(c).swipe({
			swipe: function(event, direction, distance, duration, fingerCount, fingerData) {
				if ( direction === 'left' && upage !== total_page )
				{
					href = current_url.setQuery('upage', upage + 1);
					
				}
				else if ( direction === 'right' && upage > 1 )
				{
					href = current_url.setQuery('upage', upage - 1);
				}
				if ( href )
				{
					if ( pager_ajax )
					{
						ajaxDefault(href);
					}
					else
					{
						location.href = href;
					}
				}
				else
				{
					return false;
				}
			},
			threshold: 75,
			allowPageScroll: 'auto'
		});
	}

	if ( pager_ajax )
	{
		$('<div class="ap_pager_loading"></div>').appendTo(c);
	}

	$(b + ' a, ' + n + ' a').on('click', function(e) {
		$(this).removeAttr('target');
		if ( pager_ajax )
		{
			e.preventDefault();
			ajaxDefault($(this).attr('href'));
		}
		else
		{
			e.stopPropagation();
		}
	});

	function ajaxDefault(req_url) {
		$(c).css({
			height : $(c).height()
		});
		$(l).show();
		$.ajax ({
			global: false,
			url: req_url,
			dataType: 'html',
			success: function(data) {
				var content = $(data),
					selectedContent = content.find(c).html(),
					selectedPager = content.find(n).html();
				$(c).html(selectedContent);
				$(n).html(selectedPager);
				if ( req_url.indexOf(location.origin) === -1 )
				{
					current_url = location.origin + req_url;
				}
				else
				{
					current_url = req_url;
				}
			},
			complete: function() {
				if ( pager_ajax_offset && $(pager_ajax_offset).length > 0 )
				{
					if ( $(pager_ajax_offset).length > 1 )
					{
						pager_ajax_offset = pager_ajax_offset + ':eq(0)';
					}
					$('html, body').animate({
						scrollTop : $(pager_ajax_offset).offset().top
					}, 0);
				}
				var addons_scripts = [];
				if ( pager_minify_scripts )
				{
					$('body script[src^="/files/cache/assets/minified/"]').each(function(i) {
						if ( v.attr('src').indexOf('wst_unlink_document') === -1 ) {
							addons_scripts[i] = $(this).attr('src');
						}
					});
					addons_scripts.push('/files/cache/assets/minified/modules.parserlink.tpl.js.ap_parser.min.js');
				}
				else
				{
					$('body script[src^="/addons/"]').each(function(i) {
						if ( v.attr('src').indexOf('wst_unlink_document') === -1 ) {
							addons_scripts[i] = $(this).attr('src'); 
					 	}
					});
					addons_scripts.push('/modules/parserlink/tpl/js/ap_parser.js');
				}
				
				$.each(addons_scripts, function(index, value) {
					$.getScript(value);
					if ( index === addons_scripts.length - 1 )
					{
						setTimeout(function() {
							$(c).css({
								height : 'auto'
							});
						}, 100);
					}
				});'

현재 js 파일 상태 입니다.

**Comment by cydemo** [comment]
아래가 좀 잘린 것 같은데요.

```
jQuery(function($) {

	var c = '.ap_pager_content',
		b = '.ap_navi_button',
		n = '.ap_page_navigation',
		l = '.ap_pager_loading';

	if ( pager_swipe )
	{
		var upage = 1;
		if ( current_url.getQuery('upage') )
		{
			upage = Number(current_url.getQuery('upage'));
		}
		var total_page = Number($(n).find('li:last').text());
		var href = '';

		$(c).swipe({
			swipe: function(event, direction, distance, duration, fingerCount, fingerData) {
				if ( direction === 'left' && upage !== total_page )
				{
					href = current_url.setQuery('upage', upage + 1);
					
				}
				else if ( direction === 'right' && upage > 1 )
				{
					href = current_url.setQuery('upage', upage - 1);
				}
				if ( href )
				{
					if ( pager_ajax )
					{
						ajaxDefault(href);
					}
					else
					{
						location.href = href;
					}
				}
				else
				{
					return false;
				}
			},
			threshold: 75,
			allowPageScroll: 'auto'
		});
	}

	if ( pager_ajax )
	{
		$('<div class="ap_pager_loading"></div>').appendTo(c);
	}

	$(b + ' a, ' + n + ' a').on('click', function(e) {
		$(this).removeAttr('target');
		if ( pager_ajax )
		{
			e.preventDefault();
			ajaxDefault($(this).attr('href'));
		}
		else
		{
			e.stopPropagation();
		}
	});

	function ajaxDefault(req_url) {
		$(c).css({
			height : $(c).height()
		});
		$(l).show();
		$.ajax ({
			global: false,
			url: req_url,
			dataType: 'html',
			success: function(data) {
				var content = $(data),
					selectedContent = content.find(c).html(),
					selectedPager = content.find(n).html();
				$(c).html(selectedContent);
				$(n).html(selectedPager);
				if ( req_url.indexOf(location.origin) === -1 )
				{
					current_url = location.origin + req_url;
				}
				else
				{
					current_url = req_url;
				}
			},
			complete: function() {
				if ( pager_ajax_offset && $(pager_ajax_offset).length > 0 )
				{
					if ( $(pager_ajax_offset).length > 1 )
					{
						pager_ajax_offset = pager_ajax_offset + ':eq(0)';
					}
					$('html, body').animate({
						scrollTop : $(pager_ajax_offset).offset().top
					}, 0);
				}
				var addons_scripts = [];
				if ( pager_minify_scripts )
				{
					$('body script[src^="/files/cache/assets/minified/"]').each(function(i) {
						if ( $(this).attr('src').indexOf('wst_unlink_document') === -1 ) {
							addons_scripts[i] = $(this).attr('src');
						}
					});
					addons_scripts.push('/files/cache/assets/minified/modules.parserlink.tpl.js.ap_parser.min.js');
				}
				else
				{
					$('body script[src^="/addons/"]').each(function(i) {
						if ( $(this).attr('src').indexOf('wst_unlink_document') === -1 ) {
							addons_scripts[i] = $(this).attr('src'); 
						}
					});
					addons_scripts.push('/modules/parserlink/tpl/js/ap_parser.js');
				}
				
				$.each(addons_scripts, function(index, value) {
					$.getScript(value);
					if ( index === addons_scripts.length - 1 )
					{
						setTimeout(function() {
							$(c).css({
								height : 'auto'
							});
						}, 100);
					}
				});
			}
		});
	}

});
```

**Comment by socialskyo** [comment]
@cydemo 그랬군요. 위에것을 사용하니 다시 ajax 는 정상적으로 동작 합니다.^^ 다만 기존과의 차이는 잘 모르겠습니다.

위에서 말씀 드린 이미지 길이 인식 오류와 유튜브 파싱이 안되는 부분은 그대로 인것 같습니다. 

ajax 없이 쓰면 좋긴 한데...페이지를 넘기면 실제 전체 문서 조회수가 증가하는지라... 
(저는 같은 사람이 같은 책을 필요에 의해 반복해서 본다라는 기준으로 보면 본것이므로 조회수도 볼떄마다 올라가게 해두었습니다.)

**Comment by cydemo** [comment]
연구를 좀 해봤는데 역시 파서링크 모듈을 불러오는 건 역부족인 듯합니다.
모듈의 js 파일을 불러올 수는 있었는데,
1. 문제는 js 파일이 의존하는 모듈php단과 연동이 안 된다는 점
2. js 파일 자체가 xe_content 클래스를 타겟으로 하기 때문에 자칫 증복 파싱이 일어날 수 있다는 점

등 때문이었습니다.
그런 까닭에 쪽 나누기 애드온과 유튜브 파싱은 양립할 수 없다는 결론에 도달했습니다ㅜ
지금도 그렇지만 4년 전 철부지 시절에 만든 거라 많이 부족했습니다... 
죄송합니다ㅠㅠ

**Comment by socialskyo** [comment]
^^ @cydemo 괜찮습니다. 지금 그대로 잘 사용하겠습니다. ajax 모드가 아니면 모든 문제 해결인데요 뭘~
