### ISSUE TITLE
[제보] 파싱 모듈과의 호환성 개선

### ISSUE THREAD

**Issue by socialskyo** [cydemo/rx-addon-ap_pager#2]
예를 들어 파싱 모듈로 유튜브 가 자동 출력되어 있는 경우 페이지를 이동하면 유튜브가 사라지는 이슈가 있습니다. 
ajax 설정 상태에서 나타납니다.

감사합니다.

**Comment by cydemo** [comment]
오 감사합니다~
이놈의 ajax가 문제네요ㅜ
주말 중에 확인해서 손 좀 보겠습니다ㅎㅎ

**Comment by socialskyo** [comment]
^^. 감사합니다.

**Comment by cydemo** [comment]
@socialskyo 유튜브 링크가 페이지 바깥이 아니라 페이지 안쪽에 있는 경우를 말씀하시는 건가요?
페이지 바깥에 있을 경우엔 사라지지 않는 것 같아서요.

페이지 안쪽이라면, 이 애드온이 전체페이지를 불러온 뒤 감췄다가 보여주는 방식이 아니라, 페이지 이동할 때마다 그때그때 해당 부분을 로딩하는 방식이어서 페이지 안에서 로딩되던 영상 같은 것들도 리로딩되는 건 어찌 보면 당연한 거거든요.

**Comment by socialskyo** [comment]
음..잘 모르겠습니다만....타운 쪽지로 현 상황 링크를 좀 보내 놓겠습니다.

**Comment by cydemo** [comment]
쪽지 잘 받았습니다~

어떤 이유에서인지 모르겠지만 개발자도구로 보면 유튜브 링크를 파싱한 결과가
ap_pager_content 요소 안쪽에 자리하고 있습니다.
따라서 쪽 이동을 하면 ap_pager_content 요소의 새로고침과 함께 그 안의 모든 요소가 사라지구요.

혹시 원래 에디터에서는 유튜브 링크가 첫 번째 페이지 브레이커보다 앞에 자리하는데
이게 본문으로 등록되면 링크 파싱 결과가 페이지 브레이커 안쪽으로 들어가는 오류인 건가요?

**Comment by socialskyo** [comment]
그런것 같기도 합니다. 실제 소스는 아래와 같습니다.
`

<p><a href="https://youtu.be/OaS6cMjf8vk" rel="noopener noreferrer" target="_blank">https://youtu.be/OaS6cMjf8vk</a>

<p>글 내용을 입력 합니다.</p>
<p>[%페이지구분자:여기를 기준으로 글 페이지가 넘어갑니다%]</p>
<p>2페이지 글 내용을 입력 합니다.</p>
`

**Comment by cydemo** [comment]
@socialskyo 
페이지 스타터 식별자를 넣어줘서 쪽 나누기 영역을 제한해보세요.
그러면 유튜브 영상 이후로만 쪽 나누기가 만들어질 수 있을 겁니다.
https://github.com/cydemo/rx-addon-ap_pager/blob/c80478ab8787c0004d07bc93c2bbdcae1967f8b9/conf/info.xml#L37-L40

**Comment by socialskyo** [comment]
@cydemo 네. 사실 저런 경우 그렇게 쓰긴 해야 겠네요. 공지에 반영 해두었습니다.
